# Generated by Django 2.2 on 2019-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190523_1719'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['openid', 'nickname'], name='user_openid_84b3ed_idx'),
        ),
    ]
